### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by steipete** [moqod/ios-qr-code-encoder#1]
GPL code is in conflict with the AppStore ToS and is not allowed in the store.
Also, most people probably don't feel like open sourcing their app.

Some reading material:
http://www.zdnet.com/blog/open-source/no-gpl-apps-for-apples-app-store/8046
http://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement (esp. important)

**Comment by akopanev** [comment]
The license type in the sources has been changed to MIT
