### ISSUE TITLE
fillColor not work in +[UIImage (MDQRCode) mdDrawQRCode:context:size:fillColor:]

### ISSUE THREAD

**Issue by wangyandongnx** [moqod/ios-qr-code-encoder#4]
fillColor not work in `+[UIImage (MDQRCode) mdDrawQRCode:context:size:fillColor:]`due to mismatch of color spaces.

For example,  `[UIImage mdQRCodeForString:@"Hello, world!" size:imageView.bounds.size.width fillColor:[UIColor redColor]];` returns a transparent image. 

This line `CGContextSetFillColor(ctx, CGColorGetComponents(fillColor.CGColor));` causes this issue. Replacing this line  with `CGContextSetFillColorWithColor(ctx, fillColor.CGColor);` will fix it.

**Comment by akopanev** [comment]
Thank you for reporting this issue!
Fixed.
